export const OPT_SEND = "OPT_SEND"
export const OTP_SENT_SUCCESS = "OTP_SENT_SUCCESS"
export const OTP_SENT_FAILED = "OTP_SENT_FAILED"

export const VERIFY_OTP = "VERIFY_OTP"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"

export const LOGOUT_USER = "LOGOUT_USER"

export const AUTHENTICATION = "AUTHENTICATION"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

export const INITIAL_AUTHENTICATE = "INITIAL_AUTHENTICATE"
export const INITIAL_AUTHENTICATE_SUCCESS = "INITIAL_AUTHENTICATE_SUCCESS"
export const INITIAL_AUTHENTICATE_FAILED = "INITIAL_AUTHENTICATE_FAILED"

export const UPDATE_USER = "UPDATE_USER_REQUEST"

export const USER_INACTIVE = "USER_INACTIVE"
export const RENEW_TOKEN = "RENEW_TOKEN"
