export const salesData = [
  {
    key: 0,
    event: "Sales",
    price: "0.045 ETH",
    from: "Riotracers",
    to: "A5B2R5",
    date: "19 days ago",
  },
  {
    key: 1,
    event: "Transfer",
    price: "0.045 ETH",
    from: "Riotracers",
    to: "A5B2R5",
    date: "19 days ago",
  },
  {
    key: 2,
    event: "Sales",
    price: "0.015 ETH",
    from: "Riotracers",
    to: "B32344",
    date: "21 days ago",
  },
  {
    key: 3,
    event: "Transfer",
    price: "0.015 ETH",
    from: "Riotracers",
    to: "B32344",
    date: "23 days ago",
  },
  {
    key: 0,
    event: "Sales",
    price: "0.045 ETH",
    from: "Riotracers",
    to: "A5B2R5",
    date: "19 days ago",
  },
  {
    key: 1,
    event: "Transfer",
    price: "0.045 ETH",
    from: "Riotracers",
    to: "A5B2R5",
    date: "19 days ago",
  },
  {
    key: 2,
    event: "Sales",
    price: "0.015 ETH",
    from: "Riotracers",
    to: "B32344",
    date: "21 days ago",
  },
  {
    key: 3,
    event: "Transfer",
    price: "0.015 ETH",
    from: "Riotracers",
    to: "B32344",
    date: "23 days ago",
  },
]
