export const GET_ALL_CARS = "GET_ALL_CARS"
export const GET_ALL_CARS_SUCCESS = "GET_ALL_CARS_SUCCESS"
export const GET_ALL_CARS_FAILED = "GET_ALL_CARS_FAILED"

export const RESET_ALL_CARS = "RESET_ALL_CARS"
