export const GET_ALL_CARS = "GET_ALL_CARS"
export const GET_ALL_CARS_SUCCESS = "GET_ALL_CARS_SUCCESS"
export const GET_ALL_CARS_FAILED = "GET_ALL_CARS_FAILED"

export const GET_CAR = "GET_CAR"
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS"
export const GET_CAR_FAILED = "GET_CAR_FAILED"

export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"

export const OPT_SEND = "OPT_SEND"
export const OTP_SENT_SUCCESS = "OTP_SENT_SUCCESS"
export const OTP_SENT_FAILED = "OTP_SENT_FAILED"

export const VERIFY_OTP = "VERIFY_OTP"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"

export const LOGOUT_USER = "LOGOUT_USER"

export const AUTHENTICATION = "AUTHENTICATION"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

export const INITIAL_AUTHENTICATE = "INITIAL_AUTHENTICATE"
export const INITIAL_AUTHENTICATE_SUCCESS = "INITIAL_AUTHENTICATE_SUCCESS"
export const INITIAL_AUTHENTICATE_FAILED = "INITIAL_AUTHENTICATE_FAILED"

export const GET_BALANCE = "GET_BALANCE"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED"

export const GET_GARGAGES = "GET_GARGAGES"
export const GET_GARGAGES_SUCCESS = "GET_GARGAGES_SUCCESS"
export const GET_GARGAGES_FAILED = "GET_GARGAGES_FAILED"

export const GET_STATIONS = "GET_STATIONS"
export const GET_STATIONS_SUCCESS = "GET_STATIONS_SUCCESS"
export const GET_STATIONS_FAILED = "GET_STATIONS_FAILED"

export const SET_SELECTED_CAR = "SET_SELECTED_CAR"
export const SET_SELECTED_CAR_SUCCESS = "SET_SELECTED_CAR_SUCCESS"
export const SET_SELECTED_CAR_FAILED = "SET_SELECTED_CAR_FAILED"

export const UPDATE_USER = "UPDATE_USER_REQUEST"

export const GET_PROPERTY = "GET_PROPERTY"
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS"
export const GET_PROPERTY_FAILED = "GET_PROPERTY_FAILED"
